export const ASSETS = {
  LOGO: '/images/just_logo.webp',
  NAME: '/images/karabina_name.webp',
  LOGO_CARABINER: '/CARABINER.svg',
  LOGO_FIRE: '/FIRE.svg',
  LOGO_SMOKE: '/SMOKE.svg',
  LOGO_NAME: '/images/NAME.svg',
  LOGO_NAME_JP: '/NAME_JP.svg',
  LOGO_NAME_EN: '/NAME_EN.svg',
  LOGO_CREAM_JP: '/CREAM_JP.svg',
  LOGO_CREAM_EN: '/CREAM_EN.svg',
  YOTEI: '/images/YOTEI.webp',
  HERO_VIDEO: '/hero-video.mp4',
  KARA_HOUSE: '/images/kara_house.webp',
  ATMOSPHERE: [
    '/images/atmosphere1.webp',
    '/images/atmosphere2.webp',
    '/images/atmosphere3.webp',
    '/images/atmosphere4.webp',
  ],
};
